### ISSUE TITLE
use error classes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#137]
```
Error handling in Biodiverse is run using a simple croaking mechanism.  
However, this causes complexity with the GUI's error reporting system, as the 
error text is assumed to be in the first line of the message.

Using error classes will make life easier when reporting errors.  (It is 
actually already used for errors from the PRNG, as they come as objects).
```

Original issue reported on code.google.com by `shawnlaffan` on 12 Jun 2010 at 1:10

**Comment by shawnlaffan** [comment]
Actually, error classes slow things down substantially, or at least the library that is in use in parts of the code does.  This is because it generates stack traces each time, so need to be avoided in hot paths.

Try::Tiny or similar could be used, but that can be its own issue.
