### ISSUE TITLE
Import fails for file with ñ character in the name

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#272]
```
What steps will reproduce the problem?
1.  Import a file with the ñ character in the name, e.g. ""mexaves 5 años mex"

The system throws a CSV exception.  
```

Original issue reported on code.google.com by `shawnlaffan` on 17 Nov 2011 at 4:28

===
Known steps remaining, 2019-05-06

- [X] Storable, yaml etc files  (storable files disabled for now)
- [X] Audit other text imports (non-basedata)
- [x] GUI 
Non-text imports :
- [x] shapefiles
- [X] rasters
- [x] spreadsheets

**Comment by shawnlaffan** [comment]
Possible solution could use https://metacpan.org/pod/Win32::LongPath

**Comment by shawnlaffan** [comment]
https://metacpan.org/pod/Win32::LongPath

https://metacpan.org/pod/Win32::Unicode::Dir

**Comment by shawnlaffan** [comment]
Add version 3 milestone so we test Win32::LongPath sometime soon-ish.

**Comment by shawnlaffan** [comment]
All identfied imports handle unicode where possible.  The exceptions is openoffice spreadsheets, but the underlying library does not accept file handles so it is out of our hands.
