### ISSUE TITLE
Implement a test plan

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#338]
This is a meta-issue which will be closed when the full test plan is completed. 
 It supersedes issue #133 which has been the focus of tests for the indices.  

Any new test issues should be listed here.  

Original issue reported on code.google.com by `shawnlaffan` on 25 Sep 2012 at 8:57

**Comment by shawnlaffan** [comment]
Mark as fixed.  

Test plan is relatively mature for the engine component (but not the GUI, which is untested).
