### ISSUE TITLE
Saving biodiverse maps as PDF or JPEG

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#375]
```
Dear all,
I write to ask if there is a way in Biodiverse to save or export the 
maps/figures generated directly as a PDF or JPEG for use in a publication; 
without first exporting the data into ArcGIS.
Thanks and kind regards.
Barnabas

```

Original issue reported on code.google.com by `daruna...@gmail.com` on 11 Mar 2013 at 11:29

----
2019-05-20  Remaining items

- [x]  Shift into its own export method
- [x]  Update release notes
- [x]  Blog post explaining process (draft standard)

**Comment by shawnlaffan** [comment]
Groundwork using geotiffs has been done under #684

**Comment by shawnlaffan** [comment]
Changes are on master, 2.99_004 has been released.  
Marking issue as fixed.
