### ISSUE TITLE
Spatial outputs - implement test plan

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#376]
```
Add a test plan for the spatial outputs.  

```

Original issue reported on code.google.com by `shawnlaffan` on 13 Mar 2013 at 7:33

**Comment by shawnlaffan** [comment]
Mark as fixed.  

t/27-Spatial.t contains most of the tests, but they are used extensively in other parts of the test system (e.g. the randomisation and spatial conditions tests).
