### ISSUE TITLE
GUI - shift back-end to Gtk::Builder from GladeXML

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#413]
```
Gtk2::Buildable has superseded the Gtk2::GladeXML library as the means of 
building UIs for Gtk from glade files.

As issue #5 has shown, there are also memory leaks in the GladeXML 
implementation.  Gtk2::Buildable hopefully does not.

This will also remove one dependency from the distribution, as Gtk2::Buildable 
comes as part of Gtk2.  


```

Original issue reported on code.google.com by `shawnlaffan` on 31 Oct 2013 at 4:30

**Comment by shawnlaffan** [comment]
https://developer.gnome.org/gtk2/stable/gtk-migrating-GtkBuilder.html

**Comment by andersonku** [comment]
Glade does not set the "Visible" property to "Yes" for widgets by default while converted ones do.

**Comment by shawnlaffan** [comment]
That should be OK, as we want them shown in most cases.  This will reduce the need for many of the show_all calls, although I expect leaving them be will be harmless so we won't need to audit the code for them unless they show adverse effects.

**Comment by andersonku** [comment]
From: http://developer.gimp.org/api/2.0/gtk/gtk-migrating-GtkBuilder.html
GtkBuilder can not construct partial trees, it lacks the equivalent of the root parameter of glade_xml_new(). Due to the way GtkBuilder parses its input, this is difficult to implement, see bug 447998. As a workaround, you can split your glade file into multiple GtkBuilder input files using the --root that was mentioned above.

**Comment by shawnlaffan** [comment]
That makes sense given some of the other transition docs I've seen.

We can break the various components into their own files.  These can be located under a bin/ui directory.  This process will probably simplify the transition, as the glade file can still be used while parts of it are shifted across.

**Comment by shawnlaffan** [comment]
The general approach in this looks relevant.
http://f-spot.org/gtkbuilder_transition

**Comment by andersonku** [comment]
Difficulties when converting 'hboxSpatialPage' maybe related to the fact that converter cannot handle menu:
```
andersonku@andersonku-ubuntu1404:~/biodiverse/bin/ui$ gtk-builder-convert hboxSpatialPage.glade hboxSpatialPage.ui
WARNING: duplicate id "menuitem_spatial_display"
WARNING: duplicate id "menuitem_spatial_overlays"
WARNING: duplicate id "menu_item_colour_stretch"
WARNING: duplicate id "radio_colour_stretch0"
WARNING: duplicate id "radio_colour_stretch1"
WARNING: duplicate id "radio_colour_stretch2"
WARNING: duplicate id "radio_colour_stretch3"
WARNING: duplicate id "radio_colour_stretch4"
WARNING: duplicate id "radio_colour_stretch5"
WARNING: duplicate id "radio_colour_stretch6"
WARNING: duplicate id "menuitem_spatial_colour_mode"
WARNING: duplicate id "menuitem_spatial_colour_mode_hue"
WARNING: duplicate id "menuitem_spatial_colour_mode_sat"
WARNING: duplicate id "menuitem_spatial_colour_mode_grey"
WARNING: duplicate id "menuitem_spatial_nbr_highlighting"
WARNING: duplicate id "menuitem_nbr_highlight_all"
WARNING: duplicate id "menuitem_nbr_highlight_set1"
WARNING: duplicate id "menuitem_nbr_highlight_set2"
WARNING: duplicate id "menuitem_nbr_highlight_off"
WARNING: duplicate id "menuitem_spatial_excluded_cell_colour"
WARNING: duplicate id "menuitem_spatial_undef_cell_colour"
WARNING: duplicate id "menuitem_spatial_cell_outline_colour"
WARNING: duplicate id "menuitem_spatial_cell_show_outline"
WARNING: duplicate id "menuitem_spatial_show_legend"
WARNING: duplicate id "menuitem_spatial_set_tree_line_widths"
Wrote hboxSpatialPage.ui
```
```
andersonku@andersonku-ubuntu1404:~/biodiverse/bin/ui$ ag -i menuitem_spatial_display
hboxSpatialPage.glade
164:                  <widget class="GtkMenuItem" id="menuitem_spatial_display">
hboxSpatialPage.ui
39:          <object class="GtkAction" id="menuitem_spatial_display">
40:            <property name="name">menuitem_spatial_display</property>
229:        <menu action="menuitem_spatial_display">
```

**Comment by shawnlaffan** [comment]
Updated by pull request #591 
Now for me to modify the BiodiverseGUI.pl PAR code.

**Comment by shawnlaffan** [comment]
Mark as fixed.  
Kudos to @andersonku
