### ISSUE TITLE
Indices - add species richness estimators

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#420]
```
It would be useful to add some of the richness estimators as indices.  See the 
EstimateS software for more details.  
http://viceroy.eeb.uconn.edu/estimates/EstimateSPages/EstSUsersGuide/EstimateSUs
ersGuide.htm#Appendices


```

Original issue reported on code.google.com by `shawnlaffan` on 19 Nov 2013 at 5:18

**Comment by shawnlaffan** [comment]
This issue is now close to completed. 
Need to decide whether or not to include the ACE and ICE variance estimators.  The formulae can be taken from SpadeR.

**Comment by shawnlaffan** [comment]
Now we really are close to completion.  

SpadeR also gives coverage estimates and frequencies of rare species, so we could also add those if needed.  

There are also the iChao estimators, but those could be added under their own issue.  
http://onlinelibrary.wiley.com/doi/10.1111/biom.12200/abstract

**Comment by shawnlaffan** [comment]
Mark as closed.  

The additional points in the last comment can be dealt with under new issues.
