### ISSUE TITLE
Metadata - use objects, not bare hashes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#474]
```
All metadata should use objects instead of bare hashes.  This avoids all the 
pitfalls of bare hashes, and allows all the advantages of OO.  

This needs to be done in phases, as different packages expect and use them 
differently.  

This is a meta-issue in which the respective issues listed as blockers.  

```

Original issue reported on code.google.com by `shawnlaffan` on 22 Jun 2014 at 8:49
* Blocked on: #473, #475, #476, #477, #478

**Comment by shawnlaffan** [comment]
The code to address the sub-issues has a high degree of redundancy and needs to be refactored.  That can be done under the aegis of this issue.

**Comment by shawnlaffan** [comment]
Mark as fixed.

Any gremlins can be wrangled under their own aegis.

**Comment by shawnlaffan** [comment]
Reopen.  Need to audit all occurrences of ->get_args outside of ->get_metadata\s+ subs.

**Comment by shawnlaffan** [comment]
...and close again.  All those cases are intermediate in the metadata system, i.e. they are hashes or arrays of metadata objects.
