### ISSUE TITLE
Tree metadata - use OO

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#475]
```
See issue 474 for details.  
```

Original issue reported on code.google.com by `shawnlaffan` on 22 Jun 2014 at 8:50
* Blocking: #474

**Comment by shawnlaffan** [comment]
This is a duplicate of issue #544.  While it was listed later, it applies to more packages.

**Comment by shawnlaffan** [comment]
Duplicate of #544

(trying a different approach to merging issues)

**Comment by shawnlaffan** [comment]
That doesn't seem to work, so closing again.
