### ISSUE TITLE
Basestruct metadata - use OO

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#476]
```
See issue 474 for details.  
```

Original issue reported on code.google.com by `shawnlaffan` on 22 Jun 2014 at 8:51
* Blocking: #474

**Comment by shawnlaffan** [comment]
The exports are now under issue #544 .  All that remains in this issue is get_base_stats.

**Comment by shawnlaffan** [comment]
This was merged across in 2382ea77155800290fec7a8fa8bc45a33472735d

Mark as closed.
