### ISSUE TITLE
Tree exports - nexus - add lists within the comments blocks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#503]
It would be useful to put list results within comments blocks within the 
trees.  These can be done as key=value pairs.

These can then be plotted/analysed etc using software which supports their use.

Original issue reported on code.google.com by `shawnlaffan` on 11 Sep 2014 at 6:44

To do:
- [x] add option to nexus export
- [x] update format to match spec
- [x] ensure we don't leave lists behind (clean up the comment block data as needed)
- [x] ensure colours are exported with lists if requested

**Comment by shawnlaffan** [comment]
See FigTree example data for a template.

**Comment by shawnlaffan** [comment]
Merger is pending additional items uncovered by commits in this PR.  These are in the to do list under issue #630

**Comment by shawnlaffan** [comment]
http://treegraph.bioinfweb.info/Help/wiki/Open_files#Nexus_format_with_additional_annotations

**Comment by shawnlaffan** [comment]
Changes to implement this were done under the branch for issue #630

**Comment by shawnlaffan** [comment]
Mark as fixed
