### ISSUE TITLE
Move repo to GitHub

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shawnlaffan/biodiverse#538]
```
Google Code is closing down, so it is time to shift to GitHub.

This issue is for notes and snippets related to that move.  


```

Original issue reported on code.google.com by `shawnlaffan` on 16 Mar 2015 at 1:06

**Comment by shawnlaffan** [comment]
Remaining tasks should, hopefully, just be the screenshots in the wiki.

**Comment by shawnlaffan** [comment]
Tables of contents would be useful, but they could perhaps be in their own issues.

**Comment by shawnlaffan** [comment]
Also need to handle milestones.

**Comment by shawnlaffan** [comment]
Google code repo has been updated to redirect to github.  

Mark as closed.
