### ISSUE TITLE
Biodiverse 1.0 exe file crashes on saving after randomisation

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/biodiverse#549]
The Biodiverse 1.0 executable file crashes on Windows when trying to save a basedata or project after running a randomisation.  

This also occurs when running the randomisation during the pp build phase, with error:  

[Randomise] Saving incremental basedata
[COMMON] WRITING TO FILE C:\bd_releases\biodiverse_1.0_win_x64\fname1_rand_structured_iter_1.bds.tmp
SYSTEM ERROR in executing BiodiverseGUI.pl : 65280
 at C:/strawberry_51613_x64/perl/site/lib/Module/ScanDeps.pm line 1348.

Module ScanDeps is at v 1.18.

The probable root cause in Biodiverse is a warning about Storable being passed a code ref.

**Comment by shawnlaffan** [comment]
The crash is inconsistent and might be related to a specific data set.  

To reproduce one needs to run a spatial analysis with the Phylogenetic Diversity and AED_T calculations, then try to save.  The randomisation is not needed to cause the crash.  Running only one of the calculations does not trigger the issue.  

Need to test with more data sets and try a bisect.

**Comment by shawnlaffan** [comment]
This looks to be a malformed unicode character issue.  Need to add traps at tree import time so we don't import the tree in the first place.

**Comment by shawnlaffan** [comment]
Actually, it is nothing to do with unicode. There seems to be stale/over-weakened refs in the TreeNode DESCENDENTS cache.  Not sure why they don't crop up with other data sets, though.

**Comment by shawnlaffan** [comment]
This looks to be a windows perl problem.  Cannot to reproduce on Ubuntu 14 using perlbrew (5.20.1 and 5.16.3).

**Comment by shawnlaffan** [comment]
Now that I have found the crash log, it lists the details given below.  

`
Faulting application name: perl.EXE, version: 0.0.0.0, time stamp: 0x513f0ec4
Faulting module name: ntdll.dll, version: 6.3.9600.17736, time stamp: 0x550f4336
Exception code: 0xc00000fd
Fault offset: 0x00000000000307c2
`

That exception code appears to be related to deep recursion (http://www.mikesmithdev.com/blog/debug-stack-overflow-exception/), which is not surprising given the DESCENDENTS cache contains references to all the descendant TreeNode objects, which themselves contain references to their parents and descendants.  

Data::Dumper::dump also runs out of memory when trying to dump the structure, presumably for the same reason.  YAML::Syck, however, does not.

What is odd is that none of the other trees tested cause this error, and that it happens with Strawberry perl (5.16.3) but not perlbrew on Linux.  Possibly the other trees are not as topologically deep so the recursion is not as great - need to test with a deeper alternate tree.  Also need to test using Strawberry 5.20.

**Comment by shawnlaffan** [comment]
Mark as fixed.  

This is pure speculation made without having tested on windows for 5.20, but the possible cause is the repeatable hash ordering in 5.16 and earlier, probably interacting with the PRNG used for windows.  Somehow the path taken by Clone, Storable etc ends up in an infinite recursive loop.  Without inspecting their internals it is hard to say, though.  

It would probably occur on 5.16 on Linux, but not for this data set because the order of the hash will differ.  Post 5.16 it probably wouldn't occur since the path taken through the structure will differ between runs and perhaps avoid any deep/infinite recursion, although it would probably instead become much rarer and harder to reproduce.

Or it's just a Windows perl thing.

**Comment by Sebastian-Mynott** [comment]
Please unsubscribe me from this list.

Thank you.

**Comment by shawnlaffan** [comment]
Hello Sebastian,

If you unwatch the repo in GitHub then you won't receive any further emails as issues are opened and worked on.

Shawn.
