### ISSUE TITLE
Tests - use Test::Lib to find helper module

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/biodiverse#569]
https://metacpan.org/pod/Test::Lib

This will avoid the need for rlib shenanigens if we shift to a recursive test structure.

**Comment by kappa** [comment]
Test::Lib does not provide any way to add custom paths to @INC and does not add "../lib".

So this migration will require you to change the way you run the tests.

prove -l t/ will still work, but prove -l xt/ won't as it needs t/lib/.

Still having the ability to easily manage a hierarchy inside t/ seems a valuable goal.

**Comment by kappa** [comment]
So mu suggestion is to keep rlib where it is needed, to use Test::Lib from test scripts and to add the uppermost 'lib' to @INC from outside (for example, by 'prove -l'). See pull request.

**Comment by shawnlaffan** [comment]
Thanks for the pull request @kappa
