### ISSUE TITLE
Retire Task::Biodiverse::*, move to a single cpanfile

### ISSUE THREAD

**Issue by kappa** [shawnlaffan/biodiverse#571]
See https://metacpan.org/pod/distribution/Module-CPANfile/lib/cpanfile-faq.pod

That will also allow installing author dependencies (for xt/*) which are not recorded now.

**Comment by shawnlaffan** [comment]
I agree.

I was thinking this could make things difficult for continuous integration (e.g. issue #568), but all it needs is a two line entry in the config file to (1) install dependencies using cpanm, then (2) run prove.

**Comment by shawnlaffan** [comment]
Largely addressed in 904ff3c23f486ba99b6fbb15fe98aa3c6679e118

Still to do: 
- [ ] Update installation documentation (v3 still needs the Task file due to removed dependencies)

**Comment by shawnlaffan** [comment]
Wiki updated, mark as fixed
