### ISSUE TITLE
GDAL installation on OSX

### ISSUE THREAD

**Issue by clopeza** [shawnlaffan/biodiverse#578]
After trying to install Biodiverse on Mac (OS X 10.11 El Capitan), when I try to open it (/opt/local/bin/perl BiodiverseGUI.pl) I got this warning: 

"Can't locate Geo/GDAL.pm in @INC (@INC contains:... "

I referred myself to the troubleshooting section and tried this:

"'sudo /opt/local/bin/perl -MCPAN -e 'install Geo::GDAL'"

and I got this:

"Downloading and compiling of GDAL failed.
The error is probably explained by the error log.
It is '/Users/.../.cpan/build/Geo-GDAL-2.00018-1eDeJn/gdal-build.err'.
Error validating server certificate for 'https://svn.osgeo.org:443':
- The certificate is not issued by a trusted authority. Use the
  fingerprint to validate the certificate manually!
  Certificate information:
- Hostname: *.osgeo.org
- Valid: from Mon, 02 May 2011 00:00:00 GMT until Sun, 01 May 2016 23:59:59 GMT
- Issuer: COMODO CA Limited, Salford, Greater Manchester, GB
- Fingerprint: 72:2d:b7:e7:50:6d:84:73:ed:84:c9:98:0d:0f:91:58:28:a1:28:1b
  (R)eject, accept (t)emporarily or accept (p)ermanently? svn: E175002: Unable to connect to a repository at URL 'https://svn.osgeo.org/gdal/branches/2.0/gdal'
  svn: E175002: OPTIONS of 'https://svn.osgeo.org/gdal/branches/2.0/gdal': Server certificate verification failed: issuer is not trusted (https://svn.osgeo.org)"

How can I fix this?

**Comment by shawnlaffan** [comment]
Hello Clopeza,

Thanks for the report.  It seems the Mac instructions need some updating as GDAL needs some special handling.  

Could you please try the commands below?  They are from the linux source install instructions, and I am guessing the path to the gdal-config file, so please check this is correct before running that line.  

I also don't have access to a mac, so any feedback you can provide will be very useful.  

Regards,
Shawn.

```
cpanm --look Geo::GDAL

perl Makefile.PL --no-version-check --gdal-config=/opt/local/bin/gdal-config
make
make test
make install
```

**Comment by hmarx** [comment]
Hi Clopeza and Shawn, 

I'm having the exact same issue. I tried your fix, Shawn, but am getting stuck at the second line. Error message: 

"Can't open perl script "Makefile.PL": No such file or directory"

Has there been any more progress on this issue? 

Thanks, 
Hannah

**Comment by clopeza** [comment]
Hi Hannah,
unfortunately I haven't had any luck. After trying Shawn's suggestion I got stuck with a perl package that was needed in order to install GDAL, and at that point I stopped trying on Mac and decided to move to Windows, but I'll let you guys know if I make any progress.

Cheers,
Clopeza

**Comment by shawnlaffan** [comment]
Hello Hannah (@hmarx),

Sorry for the slow response.  I've been travelling.  

The error message suggests that you are not in the Geo::GDAL folder, or possibly that the cpanm line did not work.  

Are you able to post a longer error log including the commands you typed?  If the planets and time zones align then we could also try skype or similar to speed the process up.  

Regards,
Shawn.

**Comment by andersonku** [comment]
Hi Hannah,

Can you please try the following commands?
By using the environment variable you don't have to be in the right folder to run it.
```
export PERL_GDAL_NO_VERSION_CHECK=1
export PERL_GDAL_CONFIG=/opt/local/bin/gdal-config
cpanm Geo::GDAL
```

Please let me know how it goes.

Regards,
Anderson

**Comment by haiyangzhang798** [comment]
hi all, 
I tried the suggestion above but seems mac user still have the similar problems? How to fix it rather than shifting to Windows?

**Comment by shawnlaffan** [comment]
Sorry @haiyangzhang798, there's been no luck so far.  If I can get access to an OSX machine then I can have a go at testing it as well.  

In the interim, you can run Biodiverse under a Linux virtual machine if you prefer to avoid Windows.  The speed will be affected, but it depends how large your data sets are.

**Comment by shawnlaffan** [comment]
See also the notes issue #573

**Comment by shawnlaffan** [comment]
Biodiverse now installs on MacOS, and a dmg installer is available.
https://github.com/shawnlaffan/biodiverse/wiki/Installation

@clopeza , @hmarx  and @haiyangzhang798 - please try the installers and let us know how they go.

I'll close this issue now, but it can be re-opened if need be.
