### ISSUE TITLE
installing on OSX

### ISSUE THREAD

**Issue by wf8** [shawnlaffan/biodiverse#588]
Hello,

Using the Mac install directions all the perl modules seem to install correctly. However when I try to run Biodiverse I get the errors below. Any suggestions? I'm running Yosemite 10.10.5.

Thanks!
Will

will@voltron:/Applications/biodiverse/bin$ sudo /opt/local/bin/perl5.22 BiodiverseGUI.pl
Adding BIODIVERSE_LIB paths to @INC

[USE_BASE] No user defined extensions
Invalid initialization by assignment at /Applications/biodiverse/bin/../lib/Biodiverse/Metadata/Export.pm line 16.
Compilation failed in require at /Applications/biodiverse/bin/../lib/Biodiverse/BaseStruct.pm line 41.
BEGIN failed--compilation aborted at /Applications/biodiverse/bin/../lib/Biodiverse/BaseStruct.pm line 41.
Compilation failed in require at /Applications/biodiverse/bin/../lib/Biodiverse/BaseData.pm line 34.
BEGIN failed--compilation aborted at /Applications/biodiverse/bin/../lib/Biodiverse/BaseData.pm line 34.
Compilation failed in require at /Applications/biodiverse/bin/../lib/Biodiverse/GUI/Project.pm line 9.
BEGIN failed--compilation aborted at /Applications/biodiverse/bin/../lib/Biodiverse/GUI/Project.pm line 9.
Compilation failed in require at /Applications/biodiverse/bin/../lib/Biodiverse/GUI/GUIManager.pm line 26.
Compilation failed in require at BiodiverseGUI.pl line 37.
BEGIN failed--compilation aborted at BiodiverseGUI.pl line 37.

**Comment by shawnlaffan** [comment]
Hello Will,

This is caused by a recent change in a library we are using.  

If you are using the git version then please do a git pull to update your version of the code.  

Otherwise, please edit two files as per this link (change "= (" to "=> (" in those lines):  
https://github.com/shawnlaffan/biodiverse/commit/43788b3f793da6fd4936861f3090d03fff70f604

Regards,
Shawn.

**Comment by wf8** [comment]
Thank you that helped. Now onto the GDAL installation problem...

**Comment by shawnlaffan** [comment]
See also issue #573
