### ISSUE TITLE
Basedata import error message refers to wrong column number

### ISSUE THREAD

**Issue by DanRosauer** [shawnlaffan/biodiverse#615]
When importing basedata from .csv, the 'processing errors' message refers to the wrong column number.

In this example the error states: '[BASEDATA] Non-numeric group field **in column 10** (146.0833330 ), check your data or cellsize'

But in fact the error (a hidden character) was in column 11, which caused confusion.

Perhaps the error message is referring to a zero-base index for the column number, and may be easily fixed.

A files which generates the error (using the latitude, longitude columns for groups) is attached.

![biodiverse processing error message](https://cloud.githubusercontent.com/assets/466160/18900668/32f85cba-8587-11e6-8312-7198ed8565c9.JPG)

[Camponotus Data Spreadsheet_BA.zip](https://github.com/shawnlaffan/biodiverse/files/497149/Camponotus.Data.Spreadsheet_BA.zip)

**Comment by shawnlaffan** [comment]
Thanks for the report.  The column numbers are zero based, so clarifying the error message to note that is probably the best way to go.

**Comment by shawnlaffan** [comment]
Fixed in PR #643
