### ISSUE TITLE
Tree exports - include user defined colours if set

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/biodiverse#630]
If a user has assigned colours themselves (e.g. under the processes implemented in #600) then we should allow them to be exported.  

This is simple for tabular trees, but nexus and newick need a bit of extra handling as we need to search for an ancestor that has a colour set.  

Related to #503 

Collated to do list:
- [x] Add tests for colour export functionality before merge
- [x] Option to export colours could probably be in the export metadata as a boolean.  
- [x] Exported bootstrap blocks need to have a leading ampersand, and color keyword needs to be preceded by an exclamation mark, e.g. [&!color="#00000"] instead of ["colour"="#000000"].  Otherwise FigTree does not recognise the colours.
- [x] Quotes appear optional but have no apparent effect.  Poss remove them if simple?
- [x] Needs to also apply to tabular tree.  Looks like metadata just needs to be updated.  
- [x] [[ WONTFIX - importing such data is sufficiently complex to warrant its own issue. #657 ]]  Add roundtrip tests.  SWL to generate some simple data using FigTree (which is the target package for colours).  Currently get number format errors when reading an exported file.  
- [x] Bootstrap block needs to go between label and number.  "fred[&!color=red]:5"
- [x] disable for newick - figtree seems not to support it (only Nexus)

**Comment by LukedFitzpatrick** [comment]
- [ ] Add tests for colour export functionality before merge

**Comment by shawnlaffan** [comment]
to do following brief testing:

- [ ] Option to export colours could probably be in the export metadata as a boolean.
