### ISSUE TITLE
Unable to open files on MacOS Catalina

### ISSUE THREAD

**Issue by msedaghatpour** [shawnlaffan/biodiverse#778]
I am having security/privacy issues with Biodiverse. I am unable to import or open files (example files or my own) because Biodiverse does not have permission to read the contents of my directories. Under security and privacy in system preferences, I gave Biodiverse "full disk access" and there are no other security permissions I can give.

I recently updated my computer from High Sierra to Catalina so maybe that has something to do with the problem? 
<img width="643" alt="Screen Shot 2020-11-18 at 12 32 16 PM" src="https://user-images.githubusercontent.com/31743642/99585471-3b825900-299b-11eb-9ffd-6e20025eab17.png">

**Comment by shawnlaffan** [comment]
Thanks for the report.  It could well be related to the OS version.  

Are you able to open files above the desktop level?  For example in ```/Users/maryamsedaghatpour``` instead of ```/Users/maryamsedaghatpour/Desktop```

The screenshot (thanks for providing it) also makes me wonder if there is a unicode issue.  It looks like there is a dash before ```Desktop```, so it is looking for ```/Users/maryamsedaghatpour/-Desktop```.  It might just be the GUI system hyphenating text split over two lines, though.  

Shawn.

**Comment by shawnlaffan** [comment]
Also, is it only Biodiverse files that this happens to?  A google search suggests there are many cases of other people hitting problems with file access like this.  

Rebooting the machine is one common suggestion, but often the problem returns.  There are other solutions, but I won't link to them as I do not use a Mac so can't assess how reliable they are.

**Comment by shawnlaffan** [comment]
Also reported to mailing list.  Thread starts at https://groups.google.com/g/biodiverse-users/c/bC8AhXz7Gq4/m/Lzu2cOdmCwAJ

**Comment by shawnlaffan** [comment]
An update following a debug session with Rebecca Prescott:

Files can be opened from directories other than Desktop, Documents etc.  Storing Biodiverse files in a location such as ```/home/username/biodiverse``` is one workaround.  

The error does not occur when calling the script directly from a command terminal:
```sh
/Applications/Biodiverse.app/Contents/MacOS/Biodiverse
```

@msedaghatpour - could you please try these workarounds and let me know if they work?

**Comment by msedaghatpour** [comment]
Opening it from terminal works! I am able to import data now.
Thank you for the help!

**Comment by shawnlaffan** [comment]
Thanks for confirming @msedaghatpour 

I'll re-open the issue as we still need to get the system working when called from the finder.

**Comment by shawnlaffan** [comment]
Permissions can be granted or otherwise modified under the system settings.  

Details on this Apple support page:  https://support.apple.com/en-au/guide/mac-help/mchld5a35146/mac
