### ISSUE TITLE
CANAPE analysis: Can't use string ("#NEXUS") as a HASH ref - error

### ISSUE THREAD

**Issue by gaiteiro** [shawnlaffan/biodiverse#796]
I was following the CANAPE instructions at https://biodiverse-analysis-software.blogspot.com/2014/11/do-it-yourself-canape.html and got the following error:

Can't use string ("#NEXUS") as a HASH ref while "strict refs" in use at Biodiverse/Indices.pm line 1394.
 at Biodiverse/Spatial.pm line 644.

If I'm doing anything wrong I hope you'll be able to put me on the right track (bps file attached).

Best wishes,
Michael

[NG6924.zip](https://github.com/shawnlaffan/biodiverse/files/6596697/NG6924.zip)

**Comment by shawnlaffan** [comment]
Hello Michael,

It works without problem for me using the latest source code version.  Can you let me know which version you are using?

Thanks for providing the bps file - it really helps with issues like this.  

Regards,
Shawn.

**Comment by gaiteiro** [comment]
Thanks for your help Shawn. I was using the Windows 64bit 3.1 stable version but will have a try with the development release and let you know asap.

**Comment by shawnlaffan** [comment]
The dev release won't help as it's 2.99.   I'll see if I can replicate with 3.1.

**Comment by shawnlaffan** [comment]
Works without issue for me with 3.1 when using the exe version.  Not sure what's going on here.

**Comment by shawnlaffan** [comment]
Can you send me the nexus file?

**Comment by gaiteiro** [comment]
Here it is - it was produced using a species list and the R package V.Phylomaker.

[sptree6924.zip](https://github.com/shawnlaffan/biodiverse/files/6597663/sptree6924.zip)

**Comment by shawnlaffan** [comment]
I'm still not able to reproduce.  It might be an intermittent bug, which can be very hard to diagnose.  One possibility is that the tree is not being imported correctly, as there should be no string "#NEXUS" anywhere after import.  

What happens if you reimport the tree and re-run the analyses?

And can you run the Show Labels interface successfully?  If the tree is broken then it will not display, and should throw an error.

**Comment by gaiteiro** [comment]
I tried this morning and it worked! Thanks....

The labels tab seems to display everything correctly. I'd only just installed the app so probably I should have restarted the PC before continuing.

**Comment by shawnlaffan** [comment]
Thanks for checking.  It should not need a reboot after installation, as it is just a self-extracting zip file.

Please re-open the issue if it re-occurs.
