### ISSUE TITLE
GUI does not start under macOS Sonoma

### ISSUE THREAD

**Issue by luishdez35** [shawnlaffan/biodiverse#888]
Hi
I update to SONOMA SO and Biodiverse dont start anymore

Any suggestions? 

Thanks.

**Comment by shawnlaffan** [comment]
Could you provide more details?  

Do you mean MacOS Sonoma?  
Are you running an Intel or Mac M chip?  
Which version of Biodiverse are you running?

**Comment by luishdez35** [comment]
Hi, thank you for you’re answer. 
I am running in Mac OS Sonoma with Intel and trying to run the last version for Biodiverse for intel the 4.0. 
And the problem is that just don’t open but works fine in Mac OS Big Sur. 

Thank you for your time and help.

**Comment by shawnlaffan** [comment]
@luishdez35 - I have run the mac build system to generate a new DMG for Intel.  

Can you try the DMG at this URL?  https://github.com/shawnlaffan/biodiverse_mac_build/suites/17721730921/artifacts/1014650084
(This will expire after a few weeks but that leaves plenty of time for testing).

It is built using macOS 12 (Monterey) so it remains to be seen if it runs on Sonoma.

**Comment by luishdez35** [comment]
Hello,
Thank you
I am going to try this and let you know. 

Best

**Comment by luishdez35** [comment]
Hello,
Thank you for the DMG, I just try to open and open good and run as expected.
I am going to continue used this version and let you know if something happen
Best

**Comment by shawnlaffan** [comment]
Good to hear it works. 

I'll close this issue now but feel free to open a new issue if you find other problems with the software.

If you have a general question about how to use it then there is the [discussion forum](https://github.com/shawnlaffan/biodiverse/discussions) or the [mailing list](https://groups.google.com/g/biodiverse-users/).
