### ISSUE TITLE
CANAPE: Add super category

### ISSUE THREAD

**Issue by eortizb** [shawnlaffan/biodiverse#890]
I am pleased to see that version 4.3 of Biodiverse makes an automatic categorization of the cells in a CANAPE, but to my surprise there is no super category. Doing the categorization manually I get super cells, but Biodiverse 4.3 places them as Mixed. I particularly want to compare my study with Sosa et al. 2018, who report cells with super-endemism, but I cannot make the direct comparison with my cells only as Mixed. I believe that having the super category is already part of a CANAPE canon, many works use it (for example Thornhill et al. 2016, González-Orozco et al. 2016, Dagallier et al. 2020 among many others). Biodiverse should be able to include the super category as well. Unfortunately I had to remove the Biodiverse reference from my manuscript because of this detail and put the canaper reference in its place. I want to continue using Biodiverse, I really like it! And it is my hope that CANAPE also has the super category.

**Comment by shawnlaffan** [comment]
Thanks for the request.  It will be added to the next version.  

Note that the super class can still be generated outside of Biodiverse by identifying cells with high significance for PE_WE and RPE2_NULL2.  The ```SPATIAL_RESULTS>>p_rank>>randname``` lists can be used for this (substituting the name of your randomisation for ```randname```).  

See also the details in https://biodiverse-analysis-software.blogspot.com/2023/04/changes-to-randomisation-results-p-rank.html

**Comment by shawnlaffan** [comment]
Code has been merged onto the master branch.  This issue can be closed once the following items are completed:

- [ ] Blog post published
- [ ] 4.99_002 dev release

**Comment by shawnlaffan** [comment]
4.99_002 is available, blog post is done.  Closing issue as completed.
